README.md

Add a more precise description to README.md

---

main.py

I changed logger name to be set by relative filename.

Change logger name to be set by relative filename

---

main.py

Optimize imports

---

requirements.in
requirements.txt

I added `backports.functools-lru-cache` to `requirements.in`.

Add backports.functools-lru-cache to requirements.in

---

README.md

I seted programming language for the code of `README.md`.

Set programming language for the code of README.md

---

main.py

Broke down #7 into several commits.

Refactor skipping tweets function

---

main.py

```
'ascii' codec can't encode character u'\u672c' in position 8: ordinal not in range(128)
```

Fix UnicodeEncodeError

---

main.py

- Rename "twi_api" to "api"
- Replace "api" with "self.api" in on_status()
- Change "MY_TWITTER_USERNAME" to lower case
- Add a param "api" to is_mention_or_reply_to_me()
- Remove unnecessary fields

Add main()

---

.travis.yml

ref https://blog.travis-ci.com/2012-08-13-build-workflow-around-pull-requests

Stop duplicate CI with Pull Requests

---

main.py

Fix docstrings

---

main.py
tweepy_handler.py

- Add tweepy_handler.py
- Optimize imports

Add tweepy_handler.py

---

main.py

Fix imports

---

main.py
mecab.py
tweepy_handler.py

Add the TweetHandler class

---

twitter-wordcloud-bot/main.py
twitter-wordcloud-bot/mecab.py
twitter-wordcloud-bot/tweepy_handler.py

- Move attribute to \_\_init__ method
- Also, trail redundant "return"

Fix: Instance attribute stop_words defined outside __init__

---

twitter-wordcloud-bot/tweepy_handler.py
twitter-wordcloud-bot/wordcloud_handler.py

Set encoding

---

twitter-wordcloud-bot/main.py
twitter-wordcloud-bot/tweepy_handler.py

ref https://docs.python.org/3/tutorial/modules.html#importing-from-a-package

Use "from tweepy_handler import *"

---

twitter-wordcloud-bot/main.py

Regression from #68 
I think add_to_stop_words method is redundant.

Remove add_to_stop_words method

---

requirements.in
requirements.txt
twitter-wordcloud-bot/main.py

This PR will probably resolve #19

Use backports.tempfile to create temporary folder

---

.buildpacks
buildpack-run.sh

Use mecab-ipadic-NEologd

---

app.json

Update the description in app.json
